name: codespell

on: [push, pull_request]

jobs:
  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 -m pip install codespell
      - run: codespell
