name: Quality Assurance

on: [push, pull_request]

jobs:
  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make qa-codespell

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: make qa-prettier

  ruff:
    name: Python Format and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make qa-ruff
